run:
  build-tags:
    - integration

linters-settings:
  misspell:
    locale: US
  gci:
    sections:
      - standard
      - default
    skip-generated: true

issues:
  exclude-dirs:
    - .github
  exclude-rules:
    # Do not run these linters for test files
    - path: _test\.go
      linters:
        - dupl
        - goerr113
        - containedctx
    # Do not require comments for sentinel errors
    - text: "exported: exported var Err*"
      linters:
        - revive
    # Allow long lines for //go:generate comments
    - linters:
        - lll
      source: "^//go:generate "

linters:
  # Default linters are enabled and not listed below:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace