[plugin]
name = "vm-compat"
description = "analyzes Go programs for compatibility with different Virtual Machines (VMs), specifically targeting the Cannon VM."
type = "external"

[plugin.external]
host = "github"
repo = "ChainSafe/vm-compat"
fetch = "scripts/install.sh"
list = "scripts/list.sh"
latest = "scripts/latest.sh"
parse = "scripts/parse.sh"